services:
  listmonk_db:
    image: postgres:16-alpine
    container_name: listmonk_db
    restart: unless-stopped

    environment:
      POSTGRES_DB: listmonk
      POSTGRES_USER: listmonk
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - listmonk_db_data:/var/lib/postgresql/data

    networks:
      - listmonk_net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listmonk"]
      interval: 10s
      timeout: 5s
      retries: 5


  listmonk_install:
    build:
      context: .
      dockerfile: Dockerfile.source
    image: fstack-email:latest
    container_name: listmonk_install
    restart: "no"

    depends_on:
      listmonk_db:
        condition: service_healthy

    environment:
      LISTMONK_app__address: "0.0.0.0:9000"
      LISTMONK_db__host: listmonk_db
      LISTMONK_db__port: 5432
      LISTMONK_db__user: listmonk
      LISTMONK_db__password: ${DB_PASSWORD}
      LISTMONK_db__database: listmonk
      LISTMONK_db__ssl_mode: disable
      TZ: Asia/Ho_Chi_Minh

    command:
      - "./listmonk"
      - "--install"
      - "--idempotent"
      - "--yes"
      - "--config"
      - ""

    networks:
      - listmonk_net


  listmonk:
    build:
      context: .
      dockerfile: Dockerfile.source
    image: fstack-email:latest
    container_name: listmonk
    restart: unless-stopped

    depends_on:
      listmonk_db:
        condition: service_healthy
      listmonk_install:
        condition: service_completed_successfully

    ports:
      - "9000:9000"

    environment:
      LISTMONK_app__concurrency: 1
      LISTMONK_app__message_rate: 1
      LISTMONK_app__batch_size: 1
      LISTMONK_app__address: "0.0.0.0:9000"
      LISTMONK_db__host: listmonk_db
      LISTMONK_db__port: 5432
      LISTMONK_db__user: listmonk
      LISTMONK_db__password: ${DB_PASSWORD}
      LISTMONK_db__database: listmonk
      LISTMONK_db__max_open: 50
      LISTMONK_db__max_idle: 10
      LISTMONK_db__ssl_mode: disable
      TZ: Asia/Ho_Chi_Minh

    volumes:
      - ./uploads:/listmonk/uploads

    networks:
      - listmonk_net


volumes:
  listmonk_db_data:


networks:
  listmonk_net:
    driver: bridge
